### ISSUE TITLE
Arduino and PI Issues

### ISSUE THREAD

**Issue by brcoding** [drzaiusx11/WiringVCS#1]
Just looking for a bit of clarification on the wiring.  For the Ardiuno, what are you using to get the extra analog ports, and what is best to multiplex with this so it doesn't introduce delays?

For the Raspberry PI everything was working but it would occasionally write bytes incorrectly, I suspect due to timing / noise issues. I tried increasing the READ_DELAY but it didn't seem to help even using very large values. I was using (TXS0108E) logic lever shift to go from 5 -> 3v which may have introduced some issues?

**Comment by drzaiusx11** [comment]
If you use a mega you shouldn't need a shift register to get more io ports. (I'll assume you meant digital and not analog?)

For non megas I just used a shift register (I'll need to dig up the part #)

Since the pi isn't running a real time OS, sometimes the timing fails...

**Comment by brcoding** [comment]
I figured out that 21 / 22 are the IOREF, didn't realize you could use the pins for this.

I was thinking for the PI perhaps reading the values 3x and then taking the 2 values that are the same or something similar.

I have it working on Arduino now. Thanks!

**Comment by brcoding** [comment]
Looks like I have one last issue (possibly wiring) where the bytes are exactly +1 other than FF which stays FF.

Hex output from the Ardiuno (First 16 bytes):
`
79 D9 A3 FF 9B A3 5D 21 BD F5 A9 11 8D 83 03 85
89 21 A3 F1 21 33 F1 21 57 F1 21 73 F5 21 DB F3
`
Correct source (Combat):
`
78 D8 A2 FF 9A A2 5D 20 BD F5 A9 10 8D 83 02 85
88 20 A3 F1 20 32 F0 20 57 F1 20 72 F5 20 DA F2
`

Let me know if you have a good guess, I think the wiring and pins are setup correctly but I might be overlooking something.

**Comment by brcoding** [comment]
Looks like the issue was using the TX pin even though I was using the serial over USB apparently it was causing issues. I moved D0 to pin 0 RX and everything works perfectly.

Thanks for the great library!
